import type {
  AppInfo,
  DeviceInfo,
  MCPServerStatus,
  MCPSession,
  MCPModule,
  LogEntry,
  InjectionTask,
} from "./types";

/** 模拟设备信息 */
export const mockDevice: DeviceInfo = {
  id: "emulator-5554",
  name: "Pixel 6 API 33",
  type: "usb",
  status: "connected",
  androidVersion: "13.0",
  apiLevel: 33,
  arch: "arm64-v8a",
  isRooted: true,
  fridaServerVersion: "16.5.1",
  fridaServerRunning: true,
};

/** 模拟 MCP 服务器状态 */
export const mockMCPServer: MCPServerStatus = {
  running: true,
  host: "0.0.0.0",
  port: 8768,
  transport: "sse",
  startTime: Date.now() - 1000 * 60 * 23,
  activeSessions: 2,
  totalTools: 42,
  connectedClients: 1,
};

/** 模拟应用列表 - 包含已注入和未注入的应用 */
export const mockApps: AppInfo[] = [
  {
    id: "app-1",
    packageName: "com.example.targetapp",
    appName: "目标测试应用",
    version: "3.2.1",
    versionCode: 30201,
    iconColor: "#EF4444",
    iconText: "目",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 2,
    injectionStatus: "running",
    gadgetVersion: "16.5.1",
    gadgetArch: "arm64-v8a",
    injectedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    pid: 12847,
    mcpPort: 27042,
    mcpStatus: "online",
    lastScanTime: Date.now() - 1000 * 30,
    detectionMethod: "runtime",
  },
  {
    id: "app-2",
    packageName: "com.tencent.mm",
    appName: "微信",
    version: "8.0.40",
    versionCode: 80040,
    iconColor: "#22C55E",
    iconText: "微",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 30,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 3,
    injectionStatus: "injected",
    gadgetVersion: "16.5.1",
    gadgetArch: "arm64-v8a",
    injectedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    mcpStatus: "offline",
    lastScanTime: Date.now() - 1000 * 60 * 2,
    detectionMethod: "static",
  },
  {
    id: "app-3",
    packageName: "com.sina.weibo",
    appName: "微博",
    version: "13.6.2",
    versionCode: 13062,
    iconColor: "#E11D48",
    iconText: "微",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 15,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 7,
    injectionStatus: "injected",
    gadgetVersion: "16.4.0",
    gadgetArch: "arm64-v8a",
    injectedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    mcpStatus: "offline",
    lastScanTime: Date.now() - 1000 * 60 * 5,
    detectionMethod: "static",
  },
  {
    id: "app-4",
    packageName: "com.taobao.taobao",
    appName: "淘宝",
    version: "11.8.0",
    versionCode: 118000,
    iconColor: "#F97316",
    iconText: "淘",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 20,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 5,
    injectionStatus: "not_injected",
    lastScanTime: Date.now() - 1000 * 60 * 10,
    detectionMethod: "none",
  },
  {
    id: "app-5",
    packageName: "com.ss.android.ugc.aweme",
    appName: "抖音",
    version: "24.5.0",
    versionCode: 245000,
    iconColor: "#1F2937",
    iconText: "抖",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 10,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 1,
    injectionStatus: "not_injected",
    lastScanTime: Date.now() - 1000 * 60 * 10,
    detectionMethod: "none",
  },
  {
    id: "app-6",
    packageName: "com.netease.cloudmusic",
    appName: "网易云音乐",
    version: "8.9.60",
    versionCode: 8960,
    iconColor: "#DC2626",
    iconText: "网",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 25,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 4,
    injectionStatus: "injected",
    gadgetVersion: "16.5.1",
    gadgetArch: "arm64-v8a",
    injectedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    mcpStatus: "offline",
    lastScanTime: Date.now() - 1000 * 60 * 8,
    detectionMethod: "static",
  },
  {
    id: "app-7",
    packageName: "com.zhihu.android",
    appName: "知乎",
    version: "9.34.0",
    versionCode: 9340,
    iconColor: "#2563EB",
    iconText: "知",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 18,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 6,
    injectionStatus: "error",
    gadgetVersion: "16.3.0",
    gadgetArch: "armeabi-v7a",
    injectedAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    lastScanTime: Date.now() - 1000 * 60 * 15,
    detectionMethod: "static",
  },
  {
    id: "app-8",
    packageName: "com.android.settings",
    appName: "设置",
    version: "13.0",
    versionCode: 33,
    iconColor: "#6B7280",
    iconText: "设",
    isSystem: true,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 60,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 60,
    injectionStatus: "not_injected",
    lastScanTime: Date.now() - 1000 * 60 * 10,
    detectionMethod: "none",
  },
  {
    id: "app-9",
    packageName: "com.android.chrome",
    appName: "Chrome 浏览器",
    version: "118.0.5993.80",
    versionCode: 1180599380,
    iconColor: "#0EA5E9",
    iconText: "C",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 40,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 1,
    injectionStatus: "not_injected",
    lastScanTime: Date.now() - 1000 * 60 * 10,
    detectionMethod: "none",
  },
  {
    id: "app-10",
    packageName: "com.bilibili.app",
    appName: "哔哩哔哩",
    version: "7.38.0",
    versionCode: 7380,
    iconColor: "#06B6D4",
    iconText: "B",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 12,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 2,
    injectionStatus: "injected",
    gadgetVersion: "16.5.1",
    gadgetArch: "arm64-v8a",
    injectedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    mcpStatus: "offline",
    lastScanTime: Date.now() - 1000 * 60 * 3,
    detectionMethod: "static",
  },
  {
    id: "app-11",
    packageName: "com.jingdong.app.mall",
    appName: "京东",
    version: "12.2.2",
    versionCode: 12220,
    iconColor: "#DC2626",
    iconText: "京",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 22,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 8,
    injectionStatus: "not_injected",
    lastScanTime: Date.now() - 1000 * 60 * 10,
    detectionMethod: "none",
  },
  {
    id: "app-12",
    packageName: "com.eg.android.AlipayGphone",
    appName: "支付宝",
    version: "10.5.36.8000",
    versionCode: 10536800,
    iconColor: "#2563EB",
    iconText: "支",
    isSystem: false,
    installTime: Date.now() - 1000 * 60 * 60 * 24 * 28,
    updateTime: Date.now() - 1000 * 60 * 60 * 24 * 3,
    injectionStatus: "not_injected",
    lastScanTime: Date.now() - 1000 * 60 * 10,
    detectionMethod: "none",
  },
];

/** 模拟 MCP 会话列表 */
export const mockSessions: MCPSession[] = [
  {
    id: "sess-a1b2c3",
    pid: 12847,
    appName: "目标测试应用",
    packageName: "com.example.targetapp",
    state: "attached",
    createdAt: Date.now() - 1000 * 60 * 15,
    scriptCount: 3,
    hookCount: 7,
    messageCount: 142,
  },
  {
    id: "sess-d4e5f6",
    pid: 0,
    appName: "微信",
    packageName: "com.tencent.mm",
    state: "created",
    createdAt: Date.now() - 1000 * 60 * 5,
    scriptCount: 0,
    hookCount: 0,
    messageCount: 0,
  },
];

/** MCP 模块列表 */
export const mockModules: MCPModule[] = [
  {
    name: "process",
    displayName: "进程管理",
    description: "进程列表、应用列表、启动应用、附加进程、杀死进程",
    toolCount: 8,
    icon: "Activity",
    enabled: true,
  },
  {
    name: "hook",
    displayName: "Hook 管理",
    description: "Java 方法 Hook、Native 函数 Hook、方法追踪",
    toolCount: 6,
    icon: "Anchor",
    enabled: true,
  },
  {
    name: "memory",
    displayName: "内存检查",
    description: "内存读写、内存搜索、内存扫描",
    toolCount: 5,
    icon: "Database",
    enabled: true,
  },
  {
    name: "network",
    displayName: "网络监控",
    description: "网络捕获、SSL Pinning 绕过、请求拦截",
    toolCount: 4,
    icon: "Network",
    enabled: true,
  },
  {
    name: "filesystem",
    displayName: "文件系统",
    description: "设备文件读写、目录遍历、文件搜索",
    toolCount: 5,
    icon: "FolderOpen",
    enabled: true,
  },
  {
    name: "ui_automation",
    displayName: "UI 自动化",
    description: "点击、输入、截图、UI 树分析",
    toolCount: 6,
    icon: "MousePointerClick",
    enabled: true,
  },
  {
    name: "crypto",
    displayName: "加密分析",
    description: "加密操作监控、密钥搜索、算法识别",
    toolCount: 4,
    icon: "Lock",
    enabled: true,
  },
  {
    name: "log",
    displayName: "日志捕获",
    description: "Logcat 捕获、日志过滤、日志搜索",
    toolCount: 4,
    icon: "ScrollText",
    enabled: true,
  },
];

/** 模拟日志 */
export const mockLogs: LogEntry[] = [
  {
    id: "log-1",
    timestamp: Date.now() - 1000 * 5,
    level: "info",
    source: "DeviceManager",
    message: "设备已连接: Pixel 6 API 33 (emulator-5554)",
  },
  {
    id: "log-2",
    timestamp: Date.now() - 1000 * 10,
    level: "info",
    source: "InjectionScanner",
    message: "扫描完成: 检测到 5 个已注入应用 (共 12 个应用)",
  },
  {
    id: "log-3",
    timestamp: Date.now() - 1000 * 30,
    level: "info",
    source: "MCPServer",
    message: "MCP 服务器已启动，监听 0.0.0.0:8768 (SSE)",
  },
  {
    id: "log-4",
    timestamp: Date.now() - 1000 * 60,
    level: "warning",
    source: "InjectionScanner",
    message: "应用 com.zhihu.android 的 gadget 架构不匹配 (期望 arm64-v8a, 实际 armeabi-v7a)",
  },
  {
    id: "log-5",
    timestamp: Date.now() - 1000 * 90,
    level: "info",
    source: "SessionManager",
    message: "会话 sess-a1b2c3 已附加到进程 12847 (com.example.targetapp)",
  },
  {
    id: "log-6",
    timestamp: Date.now() - 1000 * 120,
    level: "info",
    source: "FridaClient",
    message: "Hook 已安装: com.example.targetapp.LoginActivity.checkPassword()",
  },
  {
    id: "log-7",
    timestamp: Date.now() - 1000 * 180,
    level: "debug",
    source: "NetworkModule",
    message: "网络捕获已启动，SSL Pinning 绕过已注入",
  },
  {
    id: "log-8",
    timestamp: Date.now() - 1000 * 300,
    level: "error",
    source: "InjectionScanner",
    message: "无法扫描应用 com.zhihu.android: APK 解析失败",
  },
];

/** 模拟注入任务 */
export const mockInjectionTasks: InjectionTask[] = [
  {
    id: "task-1",
    apkPath: "/storage/emulated/0/Download/com.example.targetapp.apk",
    appName: "目标测试应用",
    packageName: "com.example.targetapp",
    status: "done",
    progress: 100,
    arch: "arm64-v8a",
    useApktool: true,
    outputApk: "/storage/emulated/0/Download/com.example.targetapp_injected.apk",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
];
